### ISSUE TITLE
Can't deploy to Heroku - EmberCli::DependencyError: No `ember-cli` executable found for `testapp`

### ISSUE THREAD

**Issue by shanekoss** [tricknotes/ember-cli-rails#549]
**Which operating system and version is the project developed on?**
OSX 10.11.5
**Which version of [`ruby`](https://www.ruby-lang.org/) is the project developed on?**
2.4.1
**Which version of [`npm`](https://www.npmjs.com/) is the project developed on?**
3.10.10
**Which version of [`ember-cli`](http://ember-cli.com/) is the project developed on?**
2.13.2
**What is the [`rails`](https://github.com/rails/rails) version?**
5.1.4
**What is the [`ember-cli-rails`](https://github.com/thoughtbot/ember-cli-rails) version (from `Gemfile`)?**
0.10.0
**What is the [`ember-cli-rails-addon`](https://github.com/rondale-sc/ember-cli-rails-addon/) version (from `package.json`)?**
^0.8.0
**Is your application server [multi-threaded](https://github.com/thoughtbot/ember-cli-rails/commit/ef0a49546a8c2e5fb0a298ba455fba97289065a1) 
(such as `puma` and `unicorn`) or is it multi-process (such as thin and webrick)?**
puma
**What are the contents of `config/initializers/ember.rb`?**
EmberCli.configure do |c|
  c.app :testapp
end
**How is the application deployed?**
heroku

Test app runs fine locally but getting this error when trying to deploy to heroku.

followed all steps here:  https://github.com/thoughtbot/ember-cli-rails

Any ideas?  Thanks!

```
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        npm WARN package.json @ No repository field.
remote:        npm WARN package.json @ No license field.
remote:        npm WARN build_4ed292cd43786841af9deda8a203762f No repository field.
remote:        npm WARN build_4ed292cd43786841af9deda8a203762f No license field.
remote:        rake aborted!
remote:        EmberCli::DependencyError: No `ember-cli` executable found for `testapp`.
remote:        Install it:
remote:        $ cd /tmp/build_4ed292cd43786841af9deda8a203762f/testapp
remote:        $ npm install
remote:        /tmp/build_4ed292cd43786841af9deda8a203762f/vendor/bundle/ruby/2.4.0/gems/ember-cli-rails-0.10.0/lib/ember_cli/path_set.rb:46:in `block in ember'
remote:        /tmp/build_4ed292cd43786841af9deda8a203762f/vendor/bundle/ruby/2.4.0/gems/ember-cli-rails-0.10.0/lib/ember_cli/path_set.rb:44:in `tap'
remote:        /tmp/build_4ed292cd43786841af9deda8a203762f/vendor/bundle/ruby/2.4.0/gems/ember-cli-rails-0.10.0/lib/ember_cli/path_set.rb:44:in `ember'
remote:        /tmp/build_4ed292cd43786841af9deda8a203762f/vendor/bundle/ruby/2.4.0/gems/ember-cli-rails-0.10.0/lib/ember_cli/command.rb:33:in `ember_build'
remote:        /tmp/build_4ed292cd43786841af9deda8a203762f/vendor/bundle/ruby/2.4.0/gems/ember-cli-rails-0.10.0/lib/ember_cli/command.rb:17:in `build'
remote:        /tmp/build_4ed292cd43786841af9deda8a203762f/vendor/bundle/ruby/2.4.0/gems/ember-cli-rails-0.10.0/lib/ember_cli/shell.rb:17:in `compile'
remote:        /tmp/build_4ed292cd43786841af9deda8a203762f/vendor/bundle/ruby/2.4.0/gems/ember-cli-rails-0.10.0/lib/ember_cli/app.rb:43:in `compile'
remote:        /tmp/build_4ed292cd43786841af9deda8a203762f/vendor/bundle/ruby/2.4.0/gems/ember-cli-rails-0.10.0/lib/ember_cli.rb:70:in `block in each_app'
remote:        /tmp/build_4ed292cd43786841af9deda8a203762f/vendor/bundle/ruby/2.4.0/gems/ember-cli-rails-0.10.0/lib/ember_cli.rb:70:in `each'
remote:        /tmp/build_4ed292cd43786841af9deda8a203762f/vendor/bundle/ruby/2.4.0/gems/ember-cli-rails-0.10.0/lib/ember_cli.rb:70:in `each_app'
remote:        /tmp/build_4ed292cd43786841af9deda8a203762f/vendor/bundle/ruby/2.4.0/gems/ember-cli-rails-0.10.0/lib/ember_cli.rb:52:in `compile!'
remote:        /tmp/build_4ed292cd43786841af9deda8a203762f/vendor/bundle/ruby/2.4.0/gems/ember-cli-rails-0.10.0/lib/tasks/ember-cli.rake:4:in `block (2 levels) in <top (required)>'
remote:        /tmp/build_4ed292cd43786841af9deda8a203762f/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
remote:        Tasks: TOP => assets:precompile => ember:compile
remote:        (See full trace by running task with --trace)
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed 
```

**Comment by nruth** [comment]
Did you follow https://github.com/thoughtbot/ember-cli-rails#heroku and add the nodejs buildpack?

**Comment by tricknotes** [comment]
Thanks for the report, and sorry for the long silence.

Re-checked against `main` (f1bd84a) with Node 22 / npm 10: this only happens when the build environment carries `NODE_ENV=production` (or `NPM_CONFIG_PRODUCTION=true`). `ember-cli` is a `devDependency` of the app blueprint, and `rake ember:compile` first runs `npm prune && npm install` inside the Ember app
([shell.rb](https://github.com/tricknotes/ember-cli-rails/blob/f1bd84a/lib/ember_cli/shell.rb#L63-L84));
in production mode npm skips — and `prune` removes — `devDependencies`, so
`node_modules/ember-cli/bin/ember` never exists. Without those variables the
build succeeds. (Same for `vite` on Vite-based apps; pnpm is unaffected.)

**Recommended Heroku setup**

1. `rails generate ember:heroku`, and commit the generated `package.json`
   (plus `yarn.lock` / `pnpm-lock.yaml` if you use yarn or pnpm).
2. Add the buildpacks and let the build run:

   ```sh
   $ heroku buildpacks:clear
   $ heroku buildpacks:add --index 1 heroku/nodejs
   $ heroku buildpacks:add --index 2 heroku/ruby
   $ heroku config:unset SKIP_EMBER
   ```

3. Do **not** set `NODE_ENV` / `NPM_CONFIG_PRODUCTION` as config vars —
   `assets:precompile` needs the Ember app's `devDependencies`:

   ```sh
   $ heroku config:unset NODE_ENV NPM_CONFIG_PRODUCTION
   ```

See also: https://github.com/tricknotes/ember-cli-rails#heroku

Closing as completed — please open a new issue if this still happens with the
setup above.
